/*
 Navicat Premium Data Transfer

 Source Server         : localhost3306
 Source Server Type    : MySQL
 Source Server Version : 80000
 Source Host           : localhost:3306
 Source Schema         : fxz_cloud_nacos

 Target Server Type    : MySQL
 Target Server Version : 80000
 File Encoding         : 65001

 Date: 05/04/2022 22:17:30
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for config_info
-- ----------------------------
DROP TABLE IF EXISTS `config_info`;
CREATE TABLE `config_info`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  `c_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_use` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `effect` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_schema` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfo_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info
-- ----------------------------
INSERT INTO `config_info` VALUES (1, 'fxz-auth.yaml', 'DEFAULT_GROUP', 'server:\r\n  port: 8101\r\n\r\nspring:\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: ${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n  redis:\r\n    database: 0\r\n    host: ${redis.url}\r\n    port: 6379\r\n    lettuce:\r\n      pool:\r\n        min-idle: 8\r\n        max-idle: 500\r\n        max-active: 2000\r\n        max-wait: 10000\r\n    timeout: 5000\r\n\r\n\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.common.entity.system\r\n  mapper-locations: classpath:mapper/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\nfxz:\r\n  cloud:\r\n    security:\r\n      anonUris: /token/**', '77c7dd9fe70d5c438a13a973dece76e2', '2021-12-16 18:39:32', '2022-04-05 16:36:51', NULL, '0:0:0:0:0:0:0:1', '', '', 'null', 'null', 'null', 'yaml', 'null');
INSERT INTO `config_info` VALUES (4, 'fxz-gateway.yaml', 'DEFAULT_GROUP', 'server:\r\n  port: 8301\r\nspring:\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n  cloud:\r\n    gateway:\r\n      routes:\r\n        - id: fxz-auth\r\n          uri: lb://fxz-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            - name: Hystrix\r\n              args:\r\n                name: authfallback\r\n                fallbackUri: forward:/fallback/fxz-auth\r\n        - id: fxz-server-system\r\n          uri: lb://fxz-server-system\r\n          predicates:\r\n            - Path=/system/**\r\n          filters:\r\n            - name: Hystrix\r\n              args:\r\n                name: systemfallback\r\n                fallbackUri: forward:/fallback/fxz-server-system\r\n        - id: fxz-generate\r\n          uri: lb://fxz-generate\r\n          predicates:\r\n            - Path=/generate/**\r\n        - id: fxz-job\r\n          uri: lb://fxz-job\r\n          predicates:\r\n            - Path=/schedule/**\r\n        - id: fxz-server-test\r\n          uri: lb://fxz-server-test\r\n          predicates:\r\n            - Path=/test/**\r\n          filters:\r\n            - name: Hystrix\r\n              args:\r\n                name: testfallback\r\n                fallbackUri: forward:/fallback/fxz-server-test\r\n      default-filters:\r\n        - StripPrefix=1\r\n\r\n  hystrix:\r\n    command:\r\n      default:\r\n        execution:\r\n          isolation:\r\n            thread:\r\n              timeoutInMilliseconds: 3000\r\n\r\n\r\nmanagement:\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: health,info,gateway', 'deaf0b0fe7568b471c6b459924fea55c', '2021-12-16 18:52:35', '2022-04-03 17:44:06', NULL, '0:0:0:0:0:0:0:1', '', '', 'null', 'null', 'null', 'yaml', 'null');
INSERT INTO `config_info` VALUES (5, 'fxz-server-system-test.yaml', 'DEFAULT_GROUP', 'tx-lcn:\r\n  client:\r\n    manager-address: ${fxz-tx-manager}:8888\r\n    \r\nserver:\r\n  port: 8202\r\n\r\nspring:\r\n  datasource:\r\n    dynamic:\r\n      p6spy: true\r\n      hikari:\r\n        connection-timeout: 30000\r\n        max-lifetime: 1800000\r\n        max-pool-size: 15\r\n        min-idle: 5\r\n        connection-test-query: select 1\r\n        pool-name: FxzHikariCP\r\n      primary: base\r\n      datasource:\r\n        base:\r\n          username: root\r\n          password: 127255\r\n          driver-class-name: com.mysql.cj.jdbc.Driver\r\n          url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n  autoconfigure:\r\n    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n  \r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\n  feign:\r\n    hystrix:\r\n      enabled: true\r\n  hystrix:\r\n    shareSecurityContext: true\r\n\r\n  info:\r\n    app:\r\n      name: ${spring.application.name}\r\n      description: \"@project.description@\"\r\n      version: \"@project.version@\"\r\n\r\n  management:\r\n    endpoints:\r\n      web:\r\n        exposure:\r\n          include: \'*\'\r\n    endpoint:\r\n      health:\r\n        show-details: ALWAYS\r\n\r\nmybatis-plus:\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false', '1954eb2dac5c6a7e44ca0464318a4a25', '2021-12-17 19:00:59', '2022-01-25 12:58:09', NULL, '0:0:0:0:0:0:0:1', '', '', 'null', 'null', 'null', 'yaml', 'null');
INSERT INTO `config_info` VALUES (6, 'fxz-server-system.yaml', 'DEFAULT_GROUP', 'server:\r\n  port: 8201\r\n\r\nspring:\r\n  cache:\r\n    type: redis\r\n  datasource:\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    username: root\r\n    password: 127255\r\n    url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n        \r\n  autoconfigure:\r\n    exclude: org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixAutoConfiguration\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n\r\ntx-lcn:\r\n  client:\r\n    manager-address: ${fxz-tx-manager}:8888\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.fxz.common.core.entity.system\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nfeign:\r\n  hystrix:\r\n    enabled: true\r\n\r\nhystrix:\r\n  shareSecurityContext: true\r\n\r\nfxz:\r\n  cloud:\r\n    security: \r\n      anonUris: /find,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/,/csrf,/actuator/**,/user/findByName/*,/menu/findUserPermissions/**,/user/test,/kk-anti-reptile/**\r\n\r\n# 文件系统\r\noss:\r\n  endpoint: http://47.94.42.44:9000\r\n  access-key: fxzcloud\r\n  secret-key: fxzcloud\r\n  bucketName: fxzcloud', '9f03522c1578a00979e483b732133924', '2021-12-17 19:01:56', '2022-04-04 22:45:19', NULL, '0:0:0:0:0:0:0:1', '', '', 'null', 'null', 'null', 'yaml', 'null');
INSERT INTO `config_info` VALUES (21, 'fxz-tx-manager', 'DEFAULT_GROUP', '             \r\nserver:\r\n  port: 8502\r\nspring:\r\n  datasource:\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql://${mysql.url}:3306/fxz_cloud_txmanager?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n    username: root\r\n    password: 127255\r\n  redis:\r\n    database: 0\r\n    host: ${redis.url}\r\n    port: 6379\r\n    lettuce:\r\n      pool:\r\n        min-idle: 8\r\n        max-idle: 500\r\n        max-active: 2000\r\n        max-wait: 10000\r\n    timeout: 5000\r\n\r\ntx-lcn:\r\n  manager:\r\n    # TM监听Socket端口.\r\n    port: 8888\r\n    # TM控制台密码\r\n    admin-key: 123456\r\n  logger:\r\n    # 开启日志记录\r\n    enabled: true\r\n    driver-class-name: ${spring.datasource.driver-class-name}\r\n    jdbc-url: ${spring.datasource.url}\r\n    username: ${spring.datasource.username}\r\n    password: ${spring.datasource.password}', 'd80831c901cece97069379be80bfbf7f', '2022-01-24 19:21:14', '2022-03-02 11:07:46', NULL, '0:0:0:0:0:0:0:1', '', '', 'null', 'null', 'null', 'yaml', 'null');
INSERT INTO `config_info` VALUES (70, 'fxz-generate.yaml', 'DEFAULT_GROUP', 'server:\r\n  port: 8400\r\n\r\njasypt:\r\n  encryptor:\r\n    password: fxz #根密码\r\n\r\nspring:\r\n  datasource:\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    username: root\r\n    password: 127255\r\n    url: jdbc:mysql:///fxz_cloud_codegen?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n  \r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\n\r\nmybatis-plus:\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false', '7929496227978d219137ceb498706de4', '2022-03-31 11:02:50', '2022-03-31 15:02:09', NULL, '0:0:0:0:0:0:0:1', '', '', 'null', 'null', 'null', 'yaml', 'null');
INSERT INTO `config_info` VALUES (80, 'fxz-job.yaml', 'DEFAULT_GROUP', 'server:\r\n  port: 8500\r\n\r\n\r\nspring:\r\n  datasource:\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    username: root\r\n    password: 127255\r\n    url: jdbc:mysql:///fxz_cloud_job?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n  \r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\n\r\nmybatis-plus:\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false', '61062b731e92b2c54532643ce98e9e43', '2022-04-03 17:45:50', '2022-04-03 20:01:14', NULL, '0:0:0:0:0:0:0:1', '', '', 'null', 'null', 'null', 'yaml', 'null');

-- ----------------------------
-- Table structure for config_info_aggr
-- ----------------------------
DROP TABLE IF EXISTS `config_info_aggr`;
CREATE TABLE `config_info_aggr`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `datum_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'datum_id',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '内容',
  `gmt_modified` datetime(0) NOT NULL COMMENT '修改时间',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfoaggr_datagrouptenantdatum`(`data_id`, `group_id`, `tenant_id`, `datum_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '增加租户字段' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info_aggr
-- ----------------------------

-- ----------------------------
-- Table structure for config_info_beta
-- ----------------------------
DROP TABLE IF EXISTS `config_info_beta`;
CREATE TABLE `config_info_beta`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `beta_ips` varchar(1024) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'betaIps',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfobeta_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_beta' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info_beta
-- ----------------------------

-- ----------------------------
-- Table structure for config_info_tag
-- ----------------------------
DROP TABLE IF EXISTS `config_info_tag`;
CREATE TABLE `config_info_tag`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tag_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfotag_datagrouptenanttag`(`data_id`, `group_id`, `tenant_id`, `tag_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_tag' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info_tag
-- ----------------------------

-- ----------------------------
-- Table structure for config_tags_relation
-- ----------------------------
DROP TABLE IF EXISTS `config_tags_relation`;
CREATE TABLE `config_tags_relation`  (
  `id` bigint(20) NOT NULL COMMENT 'id',
  `tag_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_name',
  `tag_type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tag_type',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `nid` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`nid`) USING BTREE,
  UNIQUE INDEX `uk_configtagrelation_configidtag`(`id`, `tag_name`, `tag_type`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_tag_relation' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_tags_relation
-- ----------------------------

-- ----------------------------
-- Table structure for group_capacity
-- ----------------------------
DROP TABLE IF EXISTS `group_capacity`;
CREATE TABLE `group_capacity`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Group ID，空字符表示整个集群',
  `quota` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数，，0表示使用默认值',
  `max_aggr_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_group_id`(`group_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '集群、各Group容量信息表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of group_capacity
-- ----------------------------

-- ----------------------------
-- Table structure for his_config_info
-- ----------------------------
DROP TABLE IF EXISTS `his_config_info`;
CREATE TABLE `his_config_info`  (
  `id` bigint(64) UNSIGNED NOT NULL,
  `nid` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `gmt_create` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00',
  `gmt_modified` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  `src_ip` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `op_type` char(10) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`nid`) USING BTREE,
  INDEX `idx_gmt_create`(`gmt_create`) USING BTREE,
  INDEX `idx_gmt_modified`(`gmt_modified`) USING BTREE,
  INDEX `idx_did`(`data_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '多租户改造' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of his_config_info
-- ----------------------------
INSERT INTO `his_config_info` VALUES (6, 57, 'fxz-server-system.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8201\r\n\r\nspring:\r\n  datasource:\r\n    dynamic:\r\n      p6spy: true\r\n      hikari:\r\n        connection-timeout: 30000\r\n        max-lifetime: 1800000\r\n        max-pool-size: 15\r\n        min-idle: 5\r\n        connection-test-query: select 1\r\n        pool-name: FxzHikariCP\r\n      primary: base\r\n      datasource:\r\n        base:\r\n          username: root\r\n          password: 127255\r\n          driver-class-name: com.mysql.cj.jdbc.Driver\r\n          url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n  autoconfigure:\r\n    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixAutoConfiguration\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n\r\ntx-lcn:\r\n  client:\r\n    manager-address: ${fxz-tx-manager}:8888\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.fxz.common.core.entity.system\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nfeign:\r\n  hystrix:\r\n    enabled: true\r\n\r\nhystrix:\r\n  shareSecurityContext: true\r\n\r\nfxz:\r\n  cloud:\r\n    security: \r\n      anonUris: /find,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/,/csrf,/actuator/**,/user/findByName/*,/menu/findUserPermissions/**,/user/test', 'fccbc8d5550b6aee64730f51f8453499', '2010-05-05 00:00:00', '2022-03-09 17:58:15', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 58, 'fxz-server-system.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8201\r\n\r\nspring:\r\n  redis:\r\n    database: 0\r\n    host: ${redis.url}\r\n    port: 6379\r\n    lettuce:\r\n      pool:\r\n        min-idle: 8\r\n        max-idle: 500\r\n        max-active: 2000\r\n        max-wait: 10000\r\n    timeout: 5000\r\n  datasource:\r\n    dynamic:\r\n      p6spy: true\r\n      hikari:\r\n        connection-timeout: 30000\r\n        max-lifetime: 1800000\r\n        max-pool-size: 15\r\n        min-idle: 5\r\n        connection-test-query: select 1\r\n        pool-name: FxzHikariCP\r\n      primary: base\r\n      datasource:\r\n        base:\r\n          username: root\r\n          password: 127255\r\n          driver-class-name: com.mysql.cj.jdbc.Driver\r\n          url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n  autoconfigure:\r\n    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixAutoConfiguration\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n\r\ntx-lcn:\r\n  client:\r\n    manager-address: ${fxz-tx-manager}:8888\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.fxz.common.core.entity.system\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nfeign:\r\n  hystrix:\r\n    enabled: true\r\n\r\nhystrix:\r\n  shareSecurityContext: true\r\n\r\nfxz:\r\n  cloud:\r\n    security: \r\n      anonUris: /find,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/,/csrf,/actuator/**,/user/findByName/*,/menu/findUserPermissions/**,/user/test', 'c0162d8445ebe138e9357df1b4903559', '2010-05-05 00:00:00', '2022-03-09 18:02:30', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 59, 'fxz-server-system.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8201\r\n\r\nspring:\r\n  datasource:\r\n    dynamic:\r\n      p6spy: true\r\n      hikari:\r\n        connection-timeout: 30000\r\n        max-lifetime: 1800000\r\n        max-pool-size: 15\r\n        min-idle: 5\r\n        connection-test-query: select 1\r\n        pool-name: FxzHikariCP\r\n      primary: base\r\n      datasource:\r\n        base:\r\n          username: root\r\n          password: 127255\r\n          driver-class-name: com.mysql.cj.jdbc.Driver\r\n          url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n  autoconfigure:\r\n    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixAutoConfiguration\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n\r\ntx-lcn:\r\n  client:\r\n    manager-address: ${fxz-tx-manager}:8888\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.fxz.common.core.entity.system\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nfeign:\r\n  hystrix:\r\n    enabled: true\r\n\r\nhystrix:\r\n  shareSecurityContext: true\r\n\r\nfxz:\r\n  cloud:\r\n    security: \r\n      anonUris: /find,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/,/csrf,/actuator/**,/user/findByName/*,/menu/findUserPermissions/**,/user/test', 'fccbc8d5550b6aee64730f51f8453499', '2010-05-05 00:00:00', '2022-03-09 19:48:50', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 60, 'fxz-server-system.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8201\r\n\r\nspring:\r\n  datasource:\r\n    dynamic:\r\n      p6spy: true\r\n      hikari:\r\n        connection-timeout: 30000\r\n        max-lifetime: 1800000\r\n        max-pool-size: 15\r\n        min-idle: 5\r\n        connection-test-query: select 1\r\n        pool-name: FxzHikariCP\r\n      primary: base\r\n      datasource:\r\n        base:\r\n          username: root\r\n          password: 127255\r\n          driver-class-name: com.mysql.cj.jdbc.Driver\r\n          url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n  autoconfigure:\r\n    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixAutoConfiguration\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n\r\ntx-lcn:\r\n  client:\r\n    manager-address: ${fxz-tx-manager}:8888\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.fxz.common.core.entity.system\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nfeign:\r\n  hystrix:\r\n    enabled: true\r\n\r\nhystrix:\r\n  shareSecurityContext: true\r\n\r\nfxz:\r\n  cloud:\r\n    security: \r\n      anonUris: /find,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/,/csrf,/actuator/**,/user/findByName/*,/menu/findUserPermissions/**,/user/test,/kk-anti-reptile/**', '85e7a77b2f67558ad0722f1d4228bb0d', '2010-05-05 00:00:00', '2022-03-25 15:16:28', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 61, 'fxz-auth.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8101\r\n\r\nspring:\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: ${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n  datasource:\r\n    dynamic:\r\n      hikari:\r\n        connection-timeout: 30000\r\n        max-lifetime: 1800000\r\n        max-pool-size: 15\r\n        min-idle: 5\r\n        connection-test-query: select 1\r\n        pool-name: FxzHikariCP\r\n      primary: base\r\n      datasource:\r\n        base:\r\n          username: root\r\n          password: 123456\r\n          driver-class-name: com.mysql.cj.jdbc.Driver\r\n          url: jdbc:mysql://124.222.103.118:3306/fxz_cloud_base?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai\r\n  redis:\r\n    database: 0\r\n    host: ${redis.url}\r\n    port: 6379\r\n    lettuce:\r\n      pool:\r\n        min-idle: 8\r\n        max-idle: 500\r\n        max-active: 2000\r\n        max-wait: 10000\r\n    timeout: 5000\r\n\r\n\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.common.entity.system\r\n  mapper-locations: classpath:mapper/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user', '30e11f3361df0ec7ee683c1decbf2aa5', '2010-05-05 00:00:00', '2022-03-27 21:59:44', NULL, '127.0.0.1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 62, 'fxz-auth.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8101\r\n\r\nspring:\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: ${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n  datasource:\r\n    dynamic:\r\n      hikari:\r\n        connection-timeout: 30000\r\n        max-lifetime: 1800000\r\n        max-pool-size: 15\r\n        min-idle: 5\r\n        connection-test-query: select 1\r\n        pool-name: FxzHikariCP\r\n      primary: base\r\n      datasource:\r\n        base:\r\n          username: root\r\n          password: 123456\r\n          driver-class-name: com.mysql.cj.jdbc.Driver\r\n          url: jdbc:mysql://124.222.103.118:3306/fxz_cloud_base?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai\r\n  redis:\r\n    database: 0\r\n    host: ${redis.url}\r\n    port: 6379\r\n    lettuce:\r\n      pool:\r\n        min-idle: 8\r\n        max-idle: 500\r\n        max-active: 2000\r\n        max-wait: 10000\r\n    timeout: 5000\r\n\r\n\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.common.entity.system\r\n  mapper-locations: classpath:mapper/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\nfxz:\r\n  cloud:\r\n    security:\r\n      innerUri: /token/**', '2c771aa4dd0b3438f368ad8f0071343f', '2010-05-05 00:00:00', '2022-03-28 15:02:57', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 63, 'fxz-server-system.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8201\r\n\r\nspring:\r\n  cache:\r\n    type: redis\r\n  datasource:\r\n    dynamic:\r\n      p6spy: true\r\n      hikari:\r\n        connection-timeout: 30000\r\n        max-lifetime: 1800000\r\n        max-pool-size: 15\r\n        min-idle: 5\r\n        connection-test-query: select 1\r\n        pool-name: FxzHikariCP\r\n      primary: base\r\n      datasource:\r\n        base:\r\n          username: root\r\n          password: 127255\r\n          driver-class-name: com.mysql.cj.jdbc.Driver\r\n          url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n  autoconfigure:\r\n    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixAutoConfiguration\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n\r\ntx-lcn:\r\n  client:\r\n    manager-address: ${fxz-tx-manager}:8888\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.fxz.common.core.entity.system\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nfeign:\r\n  hystrix:\r\n    enabled: true\r\n\r\nhystrix:\r\n  shareSecurityContext: true\r\n\r\nfxz:\r\n  cloud:\r\n    security: \r\n      anonUris: /find,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/,/csrf,/actuator/**,/user/findByName/*,/menu/findUserPermissions/**,/user/test,/kk-anti-reptile/**', 'b4aa990e9979a53e1e8d812eca759746', '2010-05-05 00:00:00', '2022-03-30 10:28:56', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 64, 'fxz-server-system.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8201\r\n\r\nspring:\r\n  cache:\r\n    type: redis\r\n  datasource:\r\n    dynamic:\r\n      p6spy: true\r\n      hikari:\r\n        connection-timeout: 30000\r\n        max-lifetime: 1800000\r\n        max-pool-size: 15\r\n        min-idle: 5\r\n        connection-test-query: select 1\r\n        pool-name: FxzHikariCP\r\n      primary: master\r\n      datasource:\r\n        master_1:\r\n          username: root\r\n          password: 127255\r\n          driver-class-name: com.mysql.cj.jdbc.Driver\r\n          url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n        slave_1:\r\n          username: root\r\n          password: 123456\r\n          driver-class-name: com.mysql.cj.jdbc.Driver\r\n          url: jdbc:mysql://124.222.103.118:3306/fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n        \r\n  autoconfigure:\r\n    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixAutoConfiguration\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n\r\ntx-lcn:\r\n  client:\r\n    manager-address: ${fxz-tx-manager}:8888\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.fxz.common.core.entity.system\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nfeign:\r\n  hystrix:\r\n    enabled: true\r\n\r\nhystrix:\r\n  shareSecurityContext: true\r\n\r\nfxz:\r\n  cloud:\r\n    security: \r\n      anonUris: /find,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/,/csrf,/actuator/**,/user/findByName/*,/menu/findUserPermissions/**,/user/test,/kk-anti-reptile/**', 'e30bb00b857fb5b7624c0d0df6003d84', '2010-05-05 00:00:00', '2022-03-31 09:39:33', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 65, 'fxz-server-system.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8201\r\n\r\nspring:\r\n  cache:\r\n    type: redis\r\n  datasource:\r\n    dynamic:\r\n      p6spy: true\r\n      hikari:\r\n        connection-timeout: 30000\r\n        max-lifetime: 1800000\r\n        max-pool-size: 15\r\n        min-idle: 5\r\n        connection-test-query: select 1\r\n        pool-name: FxzHikariCP\r\n      primary: master\r\n      datasource:\r\n        master_1:\r\n          username: root\r\n          password: 127255\r\n          driver-class-name: com.mysql.cj.jdbc.Driver\r\n          url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n        # slave_1:\r\n        #   username: root\r\n        #   password: 123456\r\n        #   driver-class-name: com.mysql.cj.jdbc.Driver\r\n        #   url: jdbc:mysql://124.222.103.118:3306/fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n        \r\n  autoconfigure:\r\n    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixAutoConfiguration\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n\r\ntx-lcn:\r\n  client:\r\n    manager-address: ${fxz-tx-manager}:8888\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.fxz.common.core.entity.system\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nfeign:\r\n  hystrix:\r\n    enabled: true\r\n\r\nhystrix:\r\n  shareSecurityContext: true\r\n\r\nfxz:\r\n  cloud:\r\n    security: \r\n      anonUris: /find,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/,/csrf,/actuator/**,/user/findByName/*,/menu/findUserPermissions/**,/user/test,/kk-anti-reptile/**', 'f989c773058983758bbb4b823ef6e213', '2010-05-05 00:00:00', '2022-03-31 09:48:15', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 66, 'fxz-server-system.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8201\r\n\r\nspring:\r\n  cache:\r\n    type: redis\r\n  datasource:\r\n    dynamic:\r\n      p6spy: true\r\n      hikari:\r\n        connection-timeout: 30000\r\n        max-lifetime: 1800000\r\n        max-pool-size: 15\r\n        min-idle: 5\r\n        connection-test-query: select 1\r\n        pool-name: FxzHikariCP\r\n      primary: master\r\n      datasource:\r\n        master:\r\n          username: root\r\n          password: 127255\r\n          driver-class-name: com.mysql.cj.jdbc.Driver\r\n          url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n        # slave_1:\r\n        #   username: root\r\n        #   password: 123456\r\n        #   driver-class-name: com.mysql.cj.jdbc.Driver\r\n        #   url: jdbc:mysql://124.222.103.118:3306/fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n        \r\n  autoconfigure:\r\n    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixAutoConfiguration\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n\r\ntx-lcn:\r\n  client:\r\n    manager-address: ${fxz-tx-manager}:8888\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.fxz.common.core.entity.system\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nfeign:\r\n  hystrix:\r\n    enabled: true\r\n\r\nhystrix:\r\n  shareSecurityContext: true\r\n\r\nfxz:\r\n  cloud:\r\n    security: \r\n      anonUris: /find,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/,/csrf,/actuator/**,/user/findByName/*,/menu/findUserPermissions/**,/user/test,/kk-anti-reptile/**', '1bd99a4fc90bef63eea7a6d6ab34fb34', '2010-05-05 00:00:00', '2022-03-31 10:04:55', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 67, 'fxz-server-system.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8201\r\n\r\nspring:\r\n  cache:\r\n    type: redis\r\n  datasource:\r\n    dynamic:\r\n      p6spy: true\r\n      hikari:\r\n        connection-timeout: 30000\r\n        max-lifetime: 1800000\r\n        max-pool-size: 15\r\n        min-idle: 5\r\n        connection-test-query: select 1\r\n        pool-name: FxzHikariCP\r\n      primary: master\r\n      datasource:\r\n        master:\r\n          username: root\r\n          password: 127255\r\n          driver-class-name: com.mysql.cj.jdbc.Driver\r\n          url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n        # slave_1:\r\n        #   username: root\r\n        #   password: 123456\r\n        #   driver-class-name: com.mysql.cj.jdbc.Driver\r\n        #   url: jdbc:mysql://124.222.103.118:3306/fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n        \r\n  autoconfigure:\r\n    exclude: org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixAutoConfiguration\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n\r\ntx-lcn:\r\n  client:\r\n    manager-address: ${fxz-tx-manager}:8888\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.fxz.common.core.entity.system\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nfeign:\r\n  hystrix:\r\n    enabled: true\r\n\r\nhystrix:\r\n  shareSecurityContext: true\r\n\r\nfxz:\r\n  cloud:\r\n    security: \r\n      anonUris: /find,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/,/csrf,/actuator/**,/user/findByName/*,/menu/findUserPermissions/**,/user/test,/kk-anti-reptile/**', '12c0e38d40973a004e9cfe55bc2b7bbc', '2010-05-05 00:00:00', '2022-03-31 10:08:04', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 68, 'fxz-server-system.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8201\r\n\r\nspring:\r\n  cache:\r\n    type: redis\r\n  datasource:\r\n    dynamic:\r\n      p6spy: true\r\n      hikari:\r\n        connection-timeout: 30000\r\n        max-lifetime: 1800000\r\n        max-pool-size: 15\r\n        min-idle: 5\r\n        connection-test-query: select 1\r\n        pool-name: FxzHikariCP\r\n      primary: master\r\n      datasource:\r\n        master:\r\n          url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n          username: root\r\n          driver-class-name: com.mysql.cj.jdbc.Driver\r\n          password: 127255\r\n        # slave_1:\r\n        #   username: root\r\n        #   password: 123456\r\n        #   driver-class-name: com.mysql.cj.jdbc.Driver\r\n        #   url: jdbc:mysql://124.222.103.118:3306/fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n        \r\n  autoconfigure:\r\n    exclude: org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixAutoConfiguration\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n\r\ntx-lcn:\r\n  client:\r\n    manager-address: ${fxz-tx-manager}:8888\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.fxz.common.core.entity.system\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nfeign:\r\n  hystrix:\r\n    enabled: true\r\n\r\nhystrix:\r\n  shareSecurityContext: true\r\n\r\nfxz:\r\n  cloud:\r\n    security: \r\n      anonUris: /find,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/,/csrf,/actuator/**,/user/findByName/*,/menu/findUserPermissions/**,/user/test,/kk-anti-reptile/**', '4ffeea65b5dcfb2d7dd38befd3d194b6', '2010-05-05 00:00:00', '2022-03-31 10:12:36', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 69, 'fxz-server-system.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8201\r\n\r\nspring:\r\n  cache:\r\n    type: redis\r\n  datasource:\r\n    dynamic:\r\n      p6spy: true\r\n      hikari:\r\n        connection-timeout: 30000\r\n        max-lifetime: 1800000\r\n        max-pool-size: 15\r\n        min-idle: 5\r\n        connection-test-query: select 1\r\n        pool-name: FxzHikariCP\r\n      primary: master\r\n      datasource:\r\n        master:\r\n          username: root\r\n          password: 127255\r\n          driver-class-name: com.mysql.cj.jdbc.Driver\r\n          url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n        # slave_1:\r\n        #   username: root\r\n        #   password: 123456\r\n        #   driver-class-name: com.mysql.cj.jdbc.Driver\r\n        #   url: jdbc:mysql://124.222.103.118:3306/fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n        \r\n  autoconfigure:\r\n    exclude: org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixAutoConfiguration\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n\r\ntx-lcn:\r\n  client:\r\n    manager-address: ${fxz-tx-manager}:8888\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.fxz.common.core.entity.system\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nfeign:\r\n  hystrix:\r\n    enabled: true\r\n\r\nhystrix:\r\n  shareSecurityContext: true\r\n\r\nfxz:\r\n  cloud:\r\n    security: \r\n      anonUris: /find,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/,/csrf,/actuator/**,/user/findByName/*,/menu/findUserPermissions/**,/user/test,/kk-anti-reptile/**', '12c0e38d40973a004e9cfe55bc2b7bbc', '2010-05-05 00:00:00', '2022-03-31 10:33:36', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 70, 'fxz-server-system.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8201\r\n\r\nspring:\r\n  cache:\r\n    type: redis\r\n  datasource:\r\n    master:\r\n      username: root\r\n      password: 127255\r\n      driver-class-name: com.mysql.cj.jdbc.Driver\r\n      url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n        \r\n  autoconfigure:\r\n    exclude: org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixAutoConfiguration\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n\r\ntx-lcn:\r\n  client:\r\n    manager-address: ${fxz-tx-manager}:8888\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.fxz.common.core.entity.system\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nfeign:\r\n  hystrix:\r\n    enabled: true\r\n\r\nhystrix:\r\n  shareSecurityContext: true\r\n\r\nfxz:\r\n  cloud:\r\n    security: \r\n      anonUris: /find,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/,/csrf,/actuator/**,/user/findByName/*,/menu/findUserPermissions/**,/user/test,/kk-anti-reptile/**', '4de8cdf4402185b861d3c5880eb733aa', '2010-05-05 00:00:00', '2022-03-31 10:35:43', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (0, 71, 'fxz-generate.yaml', 'DEFAULT_GROUP', '', 's', '03c7c0ace395d80182db07ae2c30f034', '2010-05-05 00:00:00', '2022-03-31 11:02:50', NULL, '0:0:0:0:0:0:0:1', 'I', '');
INSERT INTO `his_config_info` VALUES (70, 72, 'fxz-generate.yaml', 'DEFAULT_GROUP', '', 's', '03c7c0ace395d80182db07ae2c30f034', '2010-05-05 00:00:00', '2022-03-31 11:05:23', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (70, 73, 'fxz-generate.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8400\r\n\r\nspring:\r\n  datasource:\r\n    dynamic:\r\n      primary: base\r\n      datasource:\r\n        base:\r\n          username: root\r\n          password: 127255\r\n          driver-class-name: com.mysql.cj.jdbc.Driver\r\n          url: jdbc:mysql:///fxz_cloud_codegen?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n  \r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\n\r\nmybatis-plus:\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false', '3a87529752567d6e4c07392a2d462eca', '2010-05-05 00:00:00', '2022-03-31 11:09:26', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (70, 74, 'fxz-generate.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8400\r\n\r\nspring:\r\n  datasource:\r\n    username: root\r\n    password: 127255\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql:///fxz_cloud_codegen?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n  \r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\n\r\nmybatis-plus:\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false', 'ecbae165185d7d553279f72ca0bc14d3', '2010-05-05 00:00:00', '2022-03-31 11:11:41', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (70, 75, 'fxz-generate.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8400\r\n\r\nspring:\r\n  datasource:\r\n    username: root\r\n    password: 127255\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n  \r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\n\r\nmybatis-plus:\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false', 'e87c98cb4b7f26c748c03137d91bdd4a', '2010-05-05 00:00:00', '2022-03-31 11:19:00', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (70, 76, 'fxz-generate.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8400\r\n\r\nspring:\r\n  datasource:\r\n    username: root\r\n    password: 127255\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql:///fxz_cloud_codegen?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n  \r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\n\r\nmybatis-plus:\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false', 'ecbae165185d7d553279f72ca0bc14d3', '2010-05-05 00:00:00', '2022-03-31 11:21:44', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (4, 77, 'fxz-gateway.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8301\r\nspring:\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n  cloud:\r\n    gateway:\r\n      routes:\r\n        - id: fxz-auth\r\n          uri: lb://fxz-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            - name: Hystrix\r\n              args:\r\n                name: authfallback\r\n                fallbackUri: forward:/fallback/fxz-auth\r\n        - id: fxz-server-system\r\n          uri: lb://fxz-server-system\r\n          predicates:\r\n            - Path=/system/**\r\n          filters:\r\n            - name: Hystrix\r\n              args:\r\n                name: systemfallback\r\n                fallbackUri: forward:/fallback/fxz-server-system\r\n        - id: fxz-server-test\r\n          uri: lb://fxz-server-test\r\n          predicates:\r\n            - Path=/test/**\r\n          filters:\r\n            - name: Hystrix\r\n              args:\r\n                name: testfallback\r\n                fallbackUri: forward:/fallback/fxz-server-test\r\n      default-filters:\r\n        - StripPrefix=1\r\n\r\n  hystrix:\r\n    command:\r\n      default:\r\n        execution:\r\n          isolation:\r\n            thread:\r\n              timeoutInMilliseconds: 3000\r\n\r\n\r\nmanagement:\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: health,info,gateway', '0bffd957472e4664069191b8a2e931b0', '2010-05-05 00:00:00', '2022-03-31 11:24:13', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (70, 78, 'fxz-generate.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8400\r\n\r\nspring:\r\n  datasource:\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    username: root\r\n    password: 127255\r\n    url: jdbc:mysql:///fxz_cloud_codegen?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n  \r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\n\r\nmybatis-plus:\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false', '3f85c141a9f093d00632febcc6aaec06', '2010-05-05 00:00:00', '2022-03-31 15:02:09', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 79, 'fxz-server-system.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8201\r\n\r\nspring:\r\n  cache:\r\n    type: redis\r\n  datasource:\r\n    username: root\r\n    password: 127255\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n        \r\n  autoconfigure:\r\n    exclude: org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixAutoConfiguration\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n\r\ntx-lcn:\r\n  client:\r\n    manager-address: ${fxz-tx-manager}:8888\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.fxz.common.core.entity.system\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nfeign:\r\n  hystrix:\r\n    enabled: true\r\n\r\nhystrix:\r\n  shareSecurityContext: true\r\n\r\nfxz:\r\n  cloud:\r\n    security: \r\n      anonUris: /find,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/,/csrf,/actuator/**,/user/findByName/*,/menu/findUserPermissions/**,/user/test,/kk-anti-reptile/**', '593a6b69517d5ad727e7c089fa0bd654', '2010-05-05 00:00:00', '2022-04-02 15:54:39', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (4, 80, 'fxz-gateway.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8301\r\nspring:\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n  cloud:\r\n    gateway:\r\n      routes:\r\n        - id: fxz-auth\r\n          uri: lb://fxz-auth\r\n          predicates:\r\n            - Path=/auth/**\r\n          filters:\r\n            - name: Hystrix\r\n              args:\r\n                name: authfallback\r\n                fallbackUri: forward:/fallback/fxz-auth\r\n        - id: fxz-server-system\r\n          uri: lb://fxz-server-system\r\n          predicates:\r\n            - Path=/system/**\r\n          filters:\r\n            - name: Hystrix\r\n              args:\r\n                name: systemfallback\r\n                fallbackUri: forward:/fallback/fxz-server-system\r\n        - id: fxz-generate\r\n          uri: lb://fxz-generate\r\n          predicates:\r\n            - Path=/generate/**\r\n        - id: fxz-server-test\r\n          uri: lb://fxz-server-test\r\n          predicates:\r\n            - Path=/test/**\r\n          filters:\r\n            - name: Hystrix\r\n              args:\r\n                name: testfallback\r\n                fallbackUri: forward:/fallback/fxz-server-test\r\n      default-filters:\r\n        - StripPrefix=1\r\n\r\n  hystrix:\r\n    command:\r\n      default:\r\n        execution:\r\n          isolation:\r\n            thread:\r\n              timeoutInMilliseconds: 3000\r\n\r\n\r\nmanagement:\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: health,info,gateway', 'd5ee2f68b2a0fd384b8233c2c1881aef', '2010-05-05 00:00:00', '2022-04-03 17:44:06', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (0, 81, 'fxz-job.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8500\r\n\r\n\r\nspring:\r\n  datasource:\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    username: root\r\n    password: 127255\r\n    url: jdbc:mysql:///fxz_cloud_codegen?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n  \r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\n\r\nmybatis-plus:\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false', 'b5d61f7a195b51bbda964f8047858557', '2010-05-05 00:00:00', '2022-04-03 17:45:50', NULL, '0:0:0:0:0:0:0:1', 'I', '');
INSERT INTO `his_config_info` VALUES (80, 82, 'fxz-job.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8500\r\n\r\n\r\nspring:\r\n  datasource:\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    username: root\r\n    password: 127255\r\n    url: jdbc:mysql:///fxz_cloud_codegen?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n  \r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\n\r\nmybatis-plus:\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false', 'b5d61f7a195b51bbda964f8047858557', '2010-05-05 00:00:00', '2022-04-03 19:52:22', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (80, 83, 'fxz-job.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8500\r\n\r\n\r\nspring:\r\n  datasource:\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    username: root\r\n    password: 127255\r\n    url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n  \r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\n\r\nmybatis-plus:\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false', '84a2139b243cd95a4c4f7453285c7a4a', '2010-05-05 00:00:00', '2022-04-03 20:01:14', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (50, 84, 'application-common.yaml', 'DEFAULT_GROUP', '', 'mysql:\r\n    url: 127.0.0.1\r\n\r\nredis:\r\n    url: 127.0.0.1\r\n\r\nrabbitmq:\r\n    url: 47.94.42.44\r\n\r\nfxz-gateway: 127.0.0.1\r\n\r\nfxz-monitor-admin: 127.0.0.1\r\n\r\nfxz-register: 127.0.0.1', '72e31b7b1627fb3f11aeed4c477468b8', '2010-05-05 00:00:00', '2022-04-04 22:43:51', NULL, '0:0:0:0:0:0:0:1', 'D', '');
INSERT INTO `his_config_info` VALUES (6, 85, 'fxz-server-system.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8201\r\n\r\nspring:\r\n  cache:\r\n    type: redis\r\n  datasource:\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    username: root\r\n    password: 127255\r\n    url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n        \r\n  autoconfigure:\r\n    exclude: org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixAutoConfiguration\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n\r\ntx-lcn:\r\n  client:\r\n    manager-address: ${fxz-tx-manager}:8888\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.fxz.common.core.entity.system\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nfeign:\r\n  hystrix:\r\n    enabled: true\r\n\r\nhystrix:\r\n  shareSecurityContext: true\r\n\r\nfxz:\r\n  cloud:\r\n    security: \r\n      anonUris: /find,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/,/csrf,/actuator/**,/user/findByName/*,/menu/findUserPermissions/**,/user/test,/kk-anti-reptile/**', '8f3bb2196411d89d8f7530100ae2cbf5', '2010-05-05 00:00:00', '2022-04-04 22:45:06', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (6, 86, 'fxz-server-system.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8201\r\n\r\nspring:\r\n  cache:\r\n    type: redis\r\n  datasource:\r\n    driver-class-name: com.mysql.cj.jdbc.Driver\r\n    username: root\r\n    password: 127255\r\n    url: jdbc:mysql:///fxz_cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8\r\n        \r\n  autoconfigure:\r\n    exclude: org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixAutoConfiguration\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: http://${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n\r\ntx-lcn:\r\n  client:\r\n    manager-address: ${fxz-tx-manager}:8888\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.fxz.common.core.entity.system\r\n  mapper-locations: classpath:mapper/*/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nfeign:\r\n  hystrix:\r\n    enabled: true\r\n\r\nhystrix:\r\n  shareSecurityContext: true\r\n\r\nfxz:\r\n  cloud:\r\n    security: \r\n      anonUris: /find,/swagger-ui.html,/webjars/**,/swagger-resources/**,/v2/api-docs/**,/,/csrf,/actuator/**,/user/findByName/*,/menu/findUserPermissions/**,/user/test,/kk-anti-reptile/**\r\n\r\n# 文件系统\r\noss:\r\n  endpoint: http://47.94.42.44:9000/\r\n  access-key: fxzcloud\r\n  secret-key: fxzcloud\r\n  bucketName: fxzcloud', 'a8e4124a14ec84bdfd35c7d0b284d17c', '2010-05-05 00:00:00', '2022-04-04 22:45:19', NULL, '0:0:0:0:0:0:0:1', 'U', '');
INSERT INTO `his_config_info` VALUES (1, 87, 'fxz-auth.yaml', 'DEFAULT_GROUP', '', 'server:\r\n  port: 8101\r\n\r\nspring:\r\n  boot:\r\n    admin:\r\n      client:\r\n        url: ${fxz-monitor-admin}:8401\r\n        username: fxz\r\n        password: 123456\r\n  redis:\r\n    database: 0\r\n    host: ${redis.url}\r\n    port: 6379\r\n    lettuce:\r\n      pool:\r\n        min-idle: 8\r\n        max-idle: 500\r\n        max-active: 2000\r\n        max-wait: 10000\r\n    timeout: 5000\r\n\r\n\r\n\r\nmybatis-plus:\r\n  type-aliases-package: com.common.entity.system\r\n  mapper-locations: classpath:mapper/*.xml\r\n  configuration:\r\n    jdbc-type-for-null: null\r\n  global-config:\r\n    banner: false\r\n\r\ninfo:\r\n  app:\r\n    name: ${spring.application.name}\r\n    description: \"@project.description@\"\r\n    version: \"@project.version@\"\r\n\r\nmanagement:\r\n  endpoints:\r\n    web:\r\n      exposure:\r\n        include: \'*\'\r\n  endpoint:\r\n    health:\r\n      show-details: ALWAYS\r\n\r\nsecurity:\r\n  oauth2:\r\n    resource:\r\n      id: ${spring.application.name}\r\n      #token-info-uri:  http://${fxz-gateway}:8301/auth/oauth/check_token\r\n      user-info-uri: http://${fxz-gateway}:8301/auth/user\r\n\r\nfxz:\r\n  cloud:\r\n    security:\r\n      innerUri: /token/**', 'f1301f0b4b822140068394822a0da0a8', '2010-05-05 00:00:00', '2022-04-05 16:36:51', NULL, '0:0:0:0:0:0:0:1', 'U', '');

-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles`  (
  `username` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `role` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of roles
-- ----------------------------
INSERT INTO `roles` VALUES ('nacos', 'ROLE_ADMIN');

-- ----------------------------
-- Table structure for tenant_capacity
-- ----------------------------
DROP TABLE IF EXISTS `tenant_capacity`;
CREATE TABLE `tenant_capacity`  (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Tenant ID',
  `quota` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数',
  `max_aggr_size` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT '2010-05-05 00:00:00' COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '租户容量信息表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tenant_capacity
-- ----------------------------

-- ----------------------------
-- Table structure for tenant_info
-- ----------------------------
DROP TABLE IF EXISTS `tenant_info`;
CREATE TABLE `tenant_info`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `kp` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'kp',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tenant_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_name',
  `tenant_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tenant_desc',
  `create_source` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'create_source',
  `gmt_create` bigint(20) NOT NULL COMMENT '创建时间',
  `gmt_modified` bigint(20) NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_info_kptenantid`(`kp`, `tenant_id`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'tenant_info' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tenant_info
-- ----------------------------

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users`  (
  `username` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `password` varchar(500) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  PRIMARY KEY (`username`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', 1);

SET FOREIGN_KEY_CHECKS = 1;
