spring:
  application:
    name: art-ai
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_HOST:art-nacos}:8848
      discovery:
        server-addr: ${NACOS_HOST:art-nacos}:8848
      username: nacos
      password: art-nacos
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:art-common.yaml
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件上传大小
      max-request-size: 100MB # 总文件上传大小
  main:
    allow-circular-references: true

tmp:
  embedding:
    host: ${PG_VECTOR_HOST:art-pg_vector}
    port: 5432
    database: art
    user: root
    password: art-pgvector-password
    dimension: 1024
    table: ai_vector_store
  graph:
    neo4j:
      user: neo4j
      password: art-neo4j-password
      host: ${GRAPH_HOST:art-neo4j}
      port: 7687

