spring:
  application:
    name: art-ai
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_HOST:art-nacos}:8848
      discovery:
        server-addr: ${NACOS_HOST:art-nacos}:8848
      username: nacos
      password: art-nacos
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:art-common.yaml
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件上传大小
      max-request-size: 100MB # 总文件上传大小
  main:
    allow-circular-references: true

tmp:
  open-ai:
    base-url: ${OPEN_AI_BASE_URL:123456}
    api-key: ${OPEN_AI_API_KEY:123456}