spring:
  application:
    name: art-ai
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_HOST:art-nacos}:8848
      discovery:
        server-addr: ${NACOS_HOST:art-nacos}:8848
      username: nacos
      password: art-nacos
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:art-common.yaml
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件上传大小
      max-request-size: 100MB # 总文件上传大小
  main:
    allow-circular-references: true

tmp:
  open-ai:
    base-url: ${OPEN_AI_BASE_URL:123456}
    api-key: ${OPEN_AI_API_KEY:123456}
  embedding:
    base-url: ${OPEN_AI_EMBEDDING_URL:123456}
    host: ${PG_VECTOR_HOST:123456}
    port: ${PG_VECTOR_HOST:5432}
    database: ${PG_VECTOR_HOST:art}
    user: ${PG_VECTOR_HOST:root}
    password: ${PG_VECTOR_HOST:art-pgvector-password}
    dimension: ${PG_VECTOR_HOST:1024}
    table: ${PG_VECTOR_HOST:ai_vector_store}
  graph:
    neo4j:
      user: ${GRAPH_USER:neo4j}
      password: ${GRAPH_PASSWORD:art-neo4j-password}
      host: ${GRAPH_HOST:127.0.0.1}
      port: ${GRAPH_PORT:7687}

